[build]
  # Base is already set to cumberlandDashboard in Netlify UI
  # So publish is relative to that â€” use "." for current dir
  base = "cumberlandDashboard"
  command = ""
  publish = "."

[[headers]]
  for = "/assets/geojson/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
